Dev
Karinka-malinka/RecoBattle pull request #1
Opened 2024-03-04 11:54 UTC by Karinka-malinka

2024-03-16 15:52 UTC, Bazys requested changes
пока несколько вопросов по самому коду.
Пока исправляй, а я продолжаю разбираться с логикой

2024-03-16 15:52 UTC, Bazys commented on internal/logger/logger.go
> +import "github.com/sirupsen/logrus"
рссмотри что нить посовременне типа zap или zerolog. А еще лучше используй стнадартный slog

2024-03-16 15:52 UTC, Bazys commented on internal/database/error.go
> +type ErrConflict struct {
у таких ошибок формат именования `XxxError`

2024-03-16 15:52 UTC, Bazys commented on internal/app/asr/yandexSpeachKit/yandexSpeachKit.go
> +	response, err := ct.client.Do(req)
не вижу закрытия `body`

2024-03-16 15:52 UTC, Bazys commented on internal/controller/router/router.go
> +		ErrorHandler: func(c echo.Context, err error) error {
раз err не используешь, заменяй на _

2024-03-16 15:52 UTC, Bazys commented on internal/database/audiofilesdb/audiofilesdb.go
> +	rows, err := qb.Select("channel_tag", "text", "start_time", "end_time").
контекст есть, почему не используешь?

2024-03-16 15:52 UTC, Bazys commented on internal/database/audiofilesdb/audiofilesdb.go
> +func NewAudioFileStore(ctx context.Context, db *sql.DB) (*AudioFileStore, error) {
а вот тут зачем контекст?

2024-03-16 15:52 UTC, Bazys commented on internal/database/userdb/userdb.go
> +func NewUserStore(ctx context.Context, db *sql.DB) (*UserStore, error) {
тоже не понятно, зачем контекст в конструкторе

2024-03-16 15:52 UTC, Bazys commented on internal/controller/handler/userhandler/userhandler.go
> +func (lh *UserHandler) RegisterHandler(e *echo.Echo, publicGroup, privateGroup *echo.Group) {
столько всего не используемого.
если сигнатура приготовлена "на вырост", пока замени неиспользуемые аргументы на _

2024-03-16 15:52 UTC, Bazys commented on internal/database/qualitycontroldb/qualitycontroldb.go
> +func NewQCStore(ctx context.Context, db *sql.DB) (*QualityControlStore, error) {
опять контекст в конструкторе.

2024-03-16 15:52 UTC, Bazys commented on internal/controller/handler/audiofileshandler/audiofileshandler.go
> +	go func() error {
горутины ошибки не возвращают - надо устраивать пляски с каналами

2024-03-16 15:52 UTC, Bazys commented on internal/controller/handler/audiofileshandler/audiofileshandler.go
> +			return err
так не работает

2024-03-16 15:52 UTC, Bazys commented on internal/controller/handler/handler.go
> +	user := c.Get("user").(*jwt.Token)
а если там что то другое лежит? может все таки проверить

2024-03-16 15:52 UTC, Bazys commented on internal/database/userdb/userdb.go
> +func (d *UserStore) GetByName(ctx context.Context, login string) (*userapp.User, error) {
код похож на код функции `GetByID` может как то унифицировать?

2024-03-18 07:03 UTC, Karinka-malinka commented on internal/database/error.go
> +type ErrConflict struct {
Скорректировала

2024-03-18 07:03 UTC, Karinka-malinka commented on internal/app/asr/yandexSpeachKit/yandexSpeachKit.go
> +	response, err := ct.client.Do(req)
закрыла

2024-03-18 07:03 UTC, Karinka-malinka commented on internal/controller/router/router.go
> +		ErrorHandler: func(c echo.Context, err error) error {
заменила

2024-03-18 07:03 UTC, Karinka-malinka commented on internal/database/audiofilesdb/audiofilesdb.go
> +	rows, err := qb.Select("channel_tag", "text", "start_time", "end_time").
теперь использую

2024-03-18 07:04 UTC, Karinka-malinka commented on internal/database/audiofilesdb/audiofilesdb.go
> +func NewAudioFileStore(ctx context.Context, db *sql.DB) (*AudioFileStore, error) {
остатки прошлого, когда таблицы создавала прям в коде, а не через миграцию. Убрала

2024-03-18 07:04 UTC, Karinka-malinka commented on internal/database/userdb/userdb.go
> +func NewUserStore(ctx context.Context, db *sql.DB) (*UserStore, error) {
остатки прошлого, когда таблицы создавала прям в коде, а не через миграцию. Убрала

2024-03-18 07:04 UTC, Karinka-malinka commented on internal/controller/handler/userhandler/userhandler.go
> +func (lh *UserHandler) RegisterHandler(e *echo.Echo, publicGroup, privateGroup *echo.Group) {
Да, сигнатура на "вырост", скорректировала на _

2024-03-18 07:05 UTC, Karinka-malinka commented on internal/database/qualitycontroldb/qualitycontroldb.go
> +func NewQCStore(ctx context.Context, db *sql.DB) (*QualityControlStore, error) {
опять остатки прошлого, когда таблицы создавала прям в коде, а не через миграцию. Убрала

2024-03-18 07:05 UTC, Karinka-malinka commented on internal/controller/handler/audiofileshandler/audiofileshandler.go
> +	go func() error {
убрала, пляски с каналами уже устроены

2024-03-18 07:06 UTC, Karinka-malinka commented on internal/controller/handler/audiofileshandler/audiofileshandler.go
> +			return err
в смысле return err не работает? Это убрала. В канал же ошибка возвращается, я это дебажила даже...

2024-03-18 07:06 UTC, Karinka-malinka commented on internal/database/userdb/userdb.go
> +func (d *UserStore) GetByName(ctx context.Context, login string) (*userapp.User, error) {
Унифицировала

2024-03-18 08:09 UTC, Karinka-malinka commented on internal/logger/logger.go
> +import "github.com/sirupsen/logrus"
выбор logrus навязан моими коллегами, с которыми планируем продолжать развивать сервис. Изменила на slog

2024-03-18 08:10 UTC, Karinka-malinka commented on internal/controller/handler/handler.go
> +	user := c.Get("user").(*jwt.Token)
Сделала проверку

2024-03-23 23:04 UTC, Bazys requested changes
основное.
Я понимаю, что ты хотела развязать выполнение хендлера от выполнения `ASRProcessing` но такое делается через каналы. реализуй через worker pool

2024-03-23 23:04 UTC, Bazys commented on internal/database/database.go
> +	DB *sql.DB
рекомендую сразу смотреть в сторону `pgxpool`

2024-03-23 23:04 UTC, Bazys commented on internal/database/database.go
> +func NewDB(ctx context.Context, ps string) (*PostgresDatabase, error) {
```suggestion
func NewDB(_ context.Context, ps string) (*PostgresDatabase, error) {
```
а в принципе он тебе тут точно нужен будет?

2024-03-23 23:04 UTC, Bazys commented on internal/database/database.go
> +	if err != nil && err != migrate.ErrNoChange {
а как же `errors.Is|As`? на работе за прямое сравнение я линейкой по рукам бью))))))

2024-03-23 23:04 UTC, Bazys commented on internal/database/database.go
> +type PostgresDatabase struct {
из других пакетов вызов выглядит как `database.PostgresDatabase`
точно нужно дважды database?

2024-03-23 23:04 UTC, Bazys commented on internal/database/userdb/userdb.go
> +	tx, err := d.db.Begin()
а зачем здесь транзакция? 
У тебя единственный insert

2024-03-23 23:04 UTC, Bazys commented on internal/database/mocks/audiofilemock.go
> +func (m *MockAudioFileStore) CreateFile(ctx context.Context, audioFile audiofilesapp.AudioFile) error {
вот чтобы вручную моки не писать пользуются интерфейсам и пакетами типа [mockery](https://github.com/vektra/mockery)

2024-03-23 23:04 UTC, Bazys commented on internal/controller/server/server.go
> +	errs, _ := errgroup.WithContext(ctx)
немного странный способ использования `errgroup`.
В данном случае простой горутины было бы достаточно - у тебя уже есть контекст для управления, который слушает interrupt сигнал.

Но это просто поворчать, не критично

2024-03-23 23:04 UTC, Bazys commented on internal/controller/server/server.go
> +	err := s.srv.Shutdown(ctx)
а вот сюда бы я в контекст добавил таймаут. Вдруг gracefull зависнет

2024-03-23 23:04 UTC, Bazys commented on internal/controller/handler/handler.go
> +		if u, ok := user.(*jwt.Token); ok {
каждый раз разбирать токен? может разбор токена положить в middleware а в контексте пусть лежит готовый user

2024-03-23 23:04 UTC, Bazys commented on internal/controller/handler/audiofileshandler/audiofileshandler.go
> +	go func() {
лямбда горутина порождает новую горутину и никак не контролирует выполнение. А в дочерней горутине используется context.Background. 
Ну вот совсем плохо, ты запросто можешь тут получить утечку горутин.
Придумай способ как контролировать. 
Почитай старую, но очень актуальную [статью](https://go.dev/blog/pipelines) в го блоге и современную [реализацию](https://pkg.go.dev/golang.org/x/sync/errgroup#example-Group-Pipeline) на `errgroup`
Либо я не понял твоего замысла, но в любом случае в выпускном проекте ты должна показать, как ты умеешь реализовывать паттерн `worker pool`

2024-03-23 23:04 UTC, Bazys commented on internal/controller/handler/audiofileshandler/audiofileshandler.go
> +		ca <- true
думаю, это можно было на WaitGroup реализовать

2024-03-23 23:04 UTC, Bazys commented on internal/app/audiofilesapp/audiofilesapp.go
> +	if err := af.audioFileStore.UpdateStatusASR(ctx, audiofile.UUID.String(), StatusPROCESSING); err != nil {
а почему нельзя сразу создать в нужном статусе? зачем дважды писать в таблицу?
Это понятно было бы если бы ты все последующие операции обернула в транзакции.

2024-03-25 06:12 UTC, Karinka-malinka commented on internal/database/database.go
> +func NewDB(ctx context.Context, ps string) (*PostgresDatabase, error) {
не нужен, убрала

2024-03-25 06:16 UTC, Karinka-malinka commented on internal/database/database.go
> +	if err != nil && err != migrate.ErrNoChange {
скопипастила кусок и не глянула на это, поправила

2024-03-25 07:51 UTC, Karinka-malinka commented on internal/database/database.go
> +	DB *sql.DB
спасибо за рекомендацию! Возможно в данном проекте в его текущем состоянии pgxpool будет лучше, но в целом у нас дальше планируется юзеров вынести в отдельную базу и, возможно, это будет не postgres

2024-03-25 07:51 UTC, Karinka-malinka commented on internal/database/database.go
> +func NewDB(ctx context.Context, ps string) (*PostgresDatabase, error) {
да, не нужен. Убрала

2024-03-25 07:52 UTC, Karinka-malinka commented on internal/database/database.go
> +type PostgresDatabase struct {
не нужно, убрала

2024-03-25 08:05 UTC, Karinka-malinka commented on internal/database/userdb/userdb.go
> +	tx, err := d.db.Begin()
убрала

2024-03-25 09:02 UTC, Karinka-malinka commented on internal/controller/handler/handler.go
> +		if u, ok := user.(*jwt.Token); ok {
добавила ParseTokenFunc в echojwt.Config, после выполнения которой в контекст пишется строка id юзера. Далее все равно проверяю не пустая ли это строка

2024-03-25 09:22 UTC, Karinka-malinka commented on internal/controller/server/server.go
> +	err := s.srv.Shutdown(ctx)
добавила

2024-03-25 09:29 UTC, Karinka-malinka commented on internal/database/mocks/audiofilemock.go
> +func (m *MockAudioFileStore) CreateFile(ctx context.Context, audioFile audiofilesapp.AudioFile) error {
ок, спасибо за совет!

2024-03-25 09:38 UTC, Karinka-malinka commented on internal/controller/server/server.go
> +	errs, _ := errgroup.WithContext(ctx)
поправила

2024-03-25 12:58 UTC, Karinka-malinka commented on internal/controller/handler/audiofileshandler/audiofileshandler.go
> +		ca <- true
на WaitGroup не получится, так как ответа от хендлера не будет. ASR может длиться до 3 часов, поэтому и вынесла в отдельную горутину - запустила и все, результат распознавания получу позже, а юзеру сразу возвращаю ответ 202 (файл загружен и отправлен на распознавание)

2024-03-25 13:01 UTC, Karinka-malinka commented on internal/app/audiofilesapp/audiofilesapp.go
> +	if err := af.audioFileStore.UpdateStatusASR(ctx, audiofile.UUID.String(), StatusPROCESSING); err != nil {
в данный момент нет смысла, можно и сразу. Это мои заготовки в интерфейсе базы данных на будущее типа обработки массива файлов от одного юзера, типа очереди. Убрала из проекта двойную смену статуса

2024-03-25 13:49 UTC, Karinka-malinka commented on internal/controller/handler/audiofileshandler/audiofileshandler.go
> +	go func() {
реализовала worker pool
errgroup добавила, пока только для SetAudioFile

Замысел прост: когда получаю пакет с файлом, то я делаю 2 действия: записываю файл в базу и хранилище, а после отправляю его на распознавание. Так как распознавание процесс не быстрый, то я просто выдаю ответ, что файл загружен и послан. А результат распознавания уже будет получен позже, посмотреть его можно будет через отдельный эндпоинт

2024-03-29 09:02 UTC, merged